name: Build & Test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build src --configuration Release
    - name: Component Tests
      run: dotnet test test/ComponentTests --configuration Release /p:CollectCoverage=true /p:CoverletOutput='../coverage/ComponentTestsCoverage.json'
    - name: Unit Tests
      run: dotnet test test/UnitTests --configuration Release /p:CollectCoverage=true /p:CoverletOutput='../coverage/UnitTestsCoverage.json'
    - name: Upload net5 Code Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./test/coverage/
        fail_ci_if_error: true
        files: ./ComponentTestsCoverage.net5.0.json,./UnitTestsCoverage.net5.0.json
        name: net5-code-coverage
        path_to_write_report: ../coverage/codecov_report.txt
        verbose: true
    - name: Upload net6 Code Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        directory: ./test/coverage/
        fail_ci_if_error: true
        files: ComponentTestsCoverage.net6.0.json,UnitTestsCoverage.net6.0.json
        name: net6-code-coverage
        path_to_write_report: ../coverage/codecov_report.txt
        verbose: true